name: Setup Git user
description: Sets the Git user and email to enable committing
author: Federico Brigante
branding:
  icon: chevron-up
  color: yellow

runs:
  using: composite
  steps:
    - run: |
      git config --global user.name "GitHub Actions"
    - run: |
      git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
