name: Setup GIT user
description: GitHub Action that sets the git user and email to enable commiting
author: Federico Brigante
branding:
  icon: chevron-up
  color: yellow
inputs:
  working-directory:
    description: 'Path within which to configure git.'
    required: false
    default: './'
runs:
  using: node12
  main: index.js
