name: Setup Git user
description: Sets the Git user and email to enable committing
author: Federico Brigante
branding:
  icon: chevron-up
  color: yellow

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        git config user.name "GitHub Actions"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
